/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedOwnersRouteImport } from './routes/_authed/owners'
import { Route as AuthedInvoicesRouteImport } from './routes/_authed/invoices'
import { Route as AuthedExportsRouteImport } from './routes/_authed/exports'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthedBookingsRouteImport } from './routes/_authed/bookings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOwnersRoute = AuthedOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesRoute = AuthedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExportsRoute = AuthedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBookingsRoute = AuthedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/bookings': typeof AuthedBookingsRoute
  '/calendar': typeof AuthedCalendarRoute
  '/exports': typeof AuthedExportsRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/owners': typeof AuthedOwnersRoute
  '/settings': typeof AuthedSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bookings': typeof AuthedBookingsRoute
  '/calendar': typeof AuthedCalendarRoute
  '/exports': typeof AuthedExportsRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/owners': typeof AuthedOwnersRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/bookings': typeof AuthedBookingsRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/exports': typeof AuthedExportsRoute
  '/_authed/invoices': typeof AuthedInvoicesRoute
  '/_authed/owners': typeof AuthedOwnersRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bookings'
    | '/calendar'
    | '/exports'
    | '/invoices'
    | '/owners'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bookings'
    | '/calendar'
    | '/exports'
    | '/invoices'
    | '/owners'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/bookings'
    | '/_authed/calendar'
    | '/_authed/exports'
    | '/_authed/invoices'
    | '/_authed/owners'
    | '/_authed/settings'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/owners': {
      id: '/_authed/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof AuthedOwnersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices': {
      id: '/_authed/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthedInvoicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exports': {
      id: '/_authed/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AuthedExportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookings': {
      id: '/_authed/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthedBookingsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBookingsRoute: typeof AuthedBookingsRoute
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedExportsRoute: typeof AuthedExportsRoute
  AuthedInvoicesRoute: typeof AuthedInvoicesRoute
  AuthedOwnersRoute: typeof AuthedOwnersRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBookingsRoute: AuthedBookingsRoute,
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedExportsRoute: AuthedExportsRoute,
  AuthedInvoicesRoute: AuthedInvoicesRoute,
  AuthedOwnersRoute: AuthedOwnersRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
